name: gma_mediation_moloco
description: 'Mediation Adapter that enables sending ad requests to the Moloco
  ad network using the google_mobile_ads plugin.'
version: 1.0.0
publish_to: none
environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads:
    git:
      url: https://github.com/TVGSOFT/googleads-mobile-flutter.git
      path: packages/google_mobile_ads
      ref: main
  plugin_platform_interface: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lint: ^2.4.0
  pigeon: ^24.1.1
flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.googlemobileads.mediation.gma_mediation_moloco
        pluginClass: GmaMediationMolocoPlugin
      ios:
        pluginClass: GmaMediationMolocoPlugin
repository: https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/mediation/gma_mediation_moloco
